export const CREATE_HEROSECTION_REQUEST = 'CREATE_HEROSECTION_REQUEST';
export const CREATE_HEROSECTION_SUCCESS = 'CREATE_HEROSECTION_SUCCESS';
export const CREATE_HEROSECTION_FAILURE = 'CREATE_HEROSECTION_FAILURE';

export const GET_HEROSECTION_REQUEST = "GET_HEROSECTION_REQUEST";
export const GET_HEROSECTION_SUCCESS = "GET_HEROSECTION_SUCCESS";
export const GET_HEROSECTION_FAILURE = "GET_HEROSECTION_FAILURE";

export const DELETE_HEROSECTION_REQUEST = "DELETE_HEROSECTION_REQUEST";
export const DELETE_HEROSECTION_SUCCESS = "DELETE_HEROSECTION_SUCCESS";
export const DELETE_HEROSECTION_FAILURE = "DELETE_HEROSECTION_FAILURE";