export const CREATE_OURBESTSELLER_REQUEST = 'CREATE_OURBESTSELLER_REQUEST';
export const CREATE_OURBESTSELLER_SUCCESS = 'CREATE_OURBESTSELLER_SUCCESS';
export const CREATE_OURBESTSELLER_FAILURE = 'CREATE_OURBESTSELLER_FAILURE';

export const GET_OURBESTSELLER_REQUEST = "GET_OURBESTSELLER_REQUEST";
export const GET_OURBESTSELLER_SUCCESS = "GET_OURBESTSELLER_SUCCESS";
export const GET_OURBESTSELLER_FAILURE = "GET_OURBESTSELLER_FAILURE";

export const DELETE_OURBESTSELLER_REQUEST = "DELETE_OURBESTSELLER_REQUEST";
export const DELETE_OURBESTSELLER_SUCCESS = "DELETE_OURBESTSELLER_SUCCESS";
export const DELETE_OURBESTSELLER_FAILURE = "DELETE_OURBESTSELLER_FAILURE";