export const CREATE_OURFEATUREDPRODUCT_REQUEST = 'CREATE_OURFEATUREDPRODUCT_REQUEST';
export const CREATE_OURFEATUREDPRODUCT_SUCCESS = 'CREATE_OURFEATUREDPRODUCT_SUCCESS';
export const CREATE_OURFEATUREDPRODUCT_FAILURE = 'CREATE_OURFEATUREDPRODUCT_FAILURE';

export const GET_OURFEATUREDPRODUCT_REQUEST = "GET_OURFEATUREDPRODUCT_REQUEST";
export const GET_OURFEATUREDPRODUCT_SUCCESS = "GET_OURFEATUREDPRODUCT_SUCCESS";
export const GET_OURFEATUREDPRODUCT_FAILURE = "GET_OURFEATUREDPRODUCT_FAILURE";

export const DELETE_OURFEATUREDPRODUCT_REQUEST = "DELETE_OURFEATUREDPRODUCT_REQUEST";
export const DELETE_OURFEATUREDPRODUCT_SUCCESS = "DELETE_OURFEATUREDPRODUCT_SUCCESS";
export const DELETE_OURFEATUREDPRODUCT_FAILURE = "DELETE_OURFEATUREDPRODUCT_FAILURE";