export const CREATE_OURPRODUCT_REQUEST = 'CREATE_OURPRODUCT_REQUEST';
export const CREATE_OURPRODUCT_SUCCESS = 'CREATE_OURPRODUCT_SUCCESS';
export const CREATE_OURPRODUCT_FAILURE = 'CREATE_OURPRODUCT_FAILURE';

export const GET_OURPRODUCT_REQUEST = "GET_OURPRODUCT_REQUEST";
export const GET_OURPRODUCT_SUCCESS = "GET_OURPRODUCT_SUCCESS";
export const GET_OURPRODUCT_FAILURE = "GET_OURPRODUCT_FAILURE";

export const DELETE_OURPRODUCT_REQUEST = "DELETE_OURPRODUCT_REQUEST";
export const DELETE_OURPRODUCT_SUCCESS = "DELETE_OURPRODUCT_SUCCESS";
export const DELETE_OURPRODUCT_FAILURE = "DELETE_OURPRODUCT_FAILURE";